In [1]:
import pandas as pd

In [4]:
pd.read_csv('data/env_wasflow.tsv.gz', compression = "gzip", on_bad_lines="warn", sep = "\t")#.head(30)

,"wst_oper,stk_flow,unit,geo\time",2018,2016,2014,2012,2010
0,"DSP_I,BAL_TRD,T,AT",8933,21728,-1862,-1543,-4301
1,"DSP_I,BAL_TRD,T,BE",-3296,218424,-38549,-19027,-3423
2,"DSP_I,BAL_TRD,T,BG",-57,-511,-59,-27,-26
3,"DSP_I,BAL_TRD,T,CY",20,193,0,0,0
4,"DSP_I,BAL_TRD,T,CZ",1298,-673,-21,-191,-66
...,...,...,...,...,...,...
1045,"TRT,IMP,T,RO",667737,0,0,0,0
1046,"TRT,IMP,T,SE",3315641,3315731,3077782,3333884,3037596
1047,"TRT,IMP,T,SI",1097665,1406386,1388644,1362571,1337712
1048,"TRT,IMP,T,SK",597232,0,0,0,0
1049,"TRT,IMP,T,UK",:,1520756,1429898,1323559,1632008